# Generated by Django 5.0.2 on 2025-11-14 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('coverage', models.CharField(max_length=255)),
                ('doctor', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('planned_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SOLICITADO', 'Solicitado'), ('AUTORIZADO', 'Autorizado'), ('MATERIAL_PENDIENTE', 'Material pendiente'), ('RECHAZO', 'Rechazo'), ('REPROGRAMADO', 'Reprogramado')], default='PENDIENTE', max_length=30)),
                ('internal_observations', models.TextField(blank=True, null=True)),
                ('external_observations', models.TextField(blank=True, null=True)),
                ('last_reprogram_date', models.DateTimeField(blank=True, null=True)),
                ('last_reprogram_reason', models.TextField(blank=True, null=True)),
                ('tracking_id', models.CharField(editable=False, max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('method', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('type', models.CharField(choices=[('CREDENCIAL', 'Credencial'), ('DNI', 'DNI'), ('ORDEN', 'Orden de intervención'), ('MATERIALES', 'Materiales'), ('ESTUDIOS', 'Estudios / HC')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.patient')),
            ],
        ),
    ]
